edition = "2023";
package th06;

import "thdef.proto";

enum Version {
    VERSION_UNDEFINED = 0;
    VERSION_ORIGINAL = 1;
    VERSION_CLASSIC = 2;
    VERSION_NEW_CLASSIC = 3;
}

enum Shot {
    REIMUA = 0;
    REIMUB = 1;
    MARISAA = 2;
    MARISAB = 3;
}

enum Mode {
    MODE_STANDARD = 0;
    MODE_CHALLENGE = 1;
}

message ReplayData {
    thdef.GameId game = 1;
    Version version = 2;
    Shot shot = 3;
    thdef.Difficulty difficulty = 4;
    uint64 score = 5;
    string date = 6;
    string name = 7;
    float slowdown = 8;
    Mode mode = 9;
    repeated StageData stages = 100;
}

message StageData {
    thdef.Stage stage = 1;
    uint64 score = 2;
    uint32 seed = 3;
    uint32 power = 4;
    uint32 lives = 5;
    uint32 bombs = 6;
    uint32 rank = 7;
}
