edition = "2023";
package th08;

import "thdef.proto";

enum Shot {
    BORDER_TEAM = 0;
    MAGIC_TEAM = 1;
    SCARLET_TEAM = 2;
    GHOST_TEAM = 3;
    REIMU = 4;
    YUKARI = 5;
    MARISA = 6;
    ALICE = 7;
    SAKUYA = 8;
    REMILIA = 9;
    YOUMU = 10;
    YUYUKO = 11;
}

enum Stage {
    STAGE_1 = 0;
    STAGE_2 = 1;
    STAGE_3 = 2;
    STAGE_4A = 3;
    STAGE_4B = 4;
    STAGE_5 = 5;
    STAGE_6A = 6;
    STAGE_6B = 7;
    STAGE_EX = 8;
}

enum Final {
    FINAL_UNKNOWN = 0;
    FINAL_A = 1;
    FINAL_B = 2;
}

message ReplayData {
    thdef.GameId game = 1;
    uint32 version = 2;
    Shot shot = 3;
    thdef.Difficulty difficulty = 4;
    uint64 score = 5;
    string date = 6;
    string name = 7;
    float slowdown = 8;
    Final final = 9;
    repeated StageData stages = 100;
}

message StageData {
    Stage stage = 1;
    uint64 score = 2;
    uint32 point_items = 3;
    uint32 graze = 4;
    uint32 time = 5;
    uint32 piv = 6;
    uint32 power = 7;
    uint32 lives = 8;
    uint32 bombs = 9;
}
