edition = "2023";
package th14;

import "thdef.proto";
import "google/protobuf/timestamp.proto";

enum Shot {
    REIMUA = 0;
    REIMUB = 1;
    MARISAA = 2;
    MARISAB = 3;
    SAKUYAA = 4;
    SAKUYAB = 5;
}

message ReplayData {
    thdef.GameId game = 1;
    uint32 version = 2;
    Shot shot = 3;
    thdef.Difficulty difficulty = 4;
    uint64 score = 5;
    google.protobuf.Timestamp timestamp = 6;
    string name = 7;
    float slowdown = 8;
    repeated StageData stages = 100;
}

message StageData {
    thdef.Stage stage = 1;
    uint64 score = 2;
    uint32 graze = 3;
    uint32 piv = 4;
    uint32 power = 5;
    uint32 lives = 6;
    uint32 life_pieces = 7;
    uint32 bombs = 8;
    uint32 bomb_pieces = 9;
}
