edition = "2023";
package th20;

import "thdef.proto";
import "google/protobuf/timestamp.proto";

enum Shot {
    REIMU = 0;
    MARISA = 1;
}

enum Stone {
    RED1 = 0;
    RED2 = 1;
    BLUE1 = 2;
    BLUE2 = 3;
    YELLOW1 = 4;
    YELLOW2 = 5;
    GREEN1 = 6;
    GREEN2 = 7;
    COMMON = 8;
}

message ReplayData {
    thdef.GameId game = 1;
    uint32 version = 2;
    Shot shot = 3;
    Stone stone_main = 4;
    Stone stone_unfocused = 5;
    Stone stone_focused = 6;
    Stone stone_passive = 7;
    thdef.Difficulty difficulty = 8;
    uint64 score = 9;
    google.protobuf.Timestamp timestamp = 10;
    string name = 11;
    float slowdown = 12;
    repeated StageData stages = 100;
}

message StageData {
    thdef.Stage stage = 1;
}
