edition = "2023";
package thdef;

enum GameId {
    THNA = 0;
    TH06 = 6;
    TH07 = 7;
    TH08 = 8;
    TH09 = 9;
    TH10 = 10;
    TH11 = 11;
    TH12 = 12;
    TH128 = 128;
    TH13 = 13;
    TH14 = 14;
    TH15 = 15;
    TH16 = 16;
    TH17 = 17;
    TH18 = 18;
    TH20 = 20;
}

enum Difficulty {
    option allow_alias = true;
    EASY = 0;
    NORMAL = 1;
    HARD = 2;
    LUNATIC = 3;
    EXTRA = 4;
    PHANTASM = 5;
    OVERDRIVE = 5;
}

enum Stage {
    STAGE_1 = 0;
    STAGE_2 = 1;
    STAGE_3 = 2;
    STAGE_4 = 3;
    STAGE_5 = 4;
    STAGE_6 = 5;
    STAGE_EX = 6;
}
